### ISSUE TITLE
Statistic Selection / Statistic Settings Scrolling

### ISSUE THREAD

**Issue by bunger20** [upcs/cs341-project-ss2020-swift#47]
For Firefox and Chrome: There is very little empty space in the “Statistic Selection” section when all of the statistics are active, which makes it hard to tell that all the statistics are actually gone, especially that scrolling down causes the entire sidebar to slide off-screen. 

For Safari (desktop and mobile): “Statistic Settings” area is not scrollable, so there are a few statistics that get pushed off-screen but can’t be clicked because the sidebar slides off-screen. Occurs when nearly all the statistics are selected.

**Comment by robinsph21** [comment]
The first issue is solved and is now pushed to the latest update.

The second will take more looking into. It might be due to the custom scrollbar that was added into the site.

**Comment by robinsph21** [comment]
@bunger20 Has the second issue been resolved by your testing yet?
