### ISSUE TITLE
Possible State Highlighting issue

### ISSUE THREAD

**Issue by robinsph21** [upcs/cs341-project-ss2020-swift#50]
There have been a couple of non-reproducible bugs that have shown up where the map is not highlight-able in the same way as it has in the past (border getting thicker, state color being a bit lighter). Refreshes seem to fix the issue, as it is not non-reproducible.

**Comment by liao21** [comment]
I am also getting this error, but sometimes it goes away when I refresh. This time, when I got it, I got this error: 
TypeError: doc is nullvisuals.js:509:19
    colorSVG http://localhost:3000/javascripts/visuals.js:509
    colorState http://localhost:3000/javascripts/visuals.js:520
    displayWeights http://localhost:3000/javascripts/model.js:197
    <anonymous> http://localhost:3000/javascripts/visuals.js:389

Maybe it has something to do with this recurring error: 
Wax initialize failed: TypeError: c is undefined SymBfwCS.js:17:477

**Comment by liao21** [comment]
I notice, there is a lag between the map load and the coloring when I get this error.

**Comment by liao21** [comment]
This time I got two of the "Wax initialize error"

**Comment by liao21** [comment]
Also, when there's no highlighting, there's no state clicking.

**Comment by liao21** [comment]
This time, I got one error: 

Wax initialize failed: TypeError: c is undefined 2 SymBfwCS.js:17:477

**Comment by regier21** [comment]
The code has been refactored and it is not clear that this is still an issue. Will reopen if it reoccurs.
