### ISSUE TITLE
State Window: Statistic Details prints the message twice sometimes

### ISSUE THREAD

**Issue by liao21** [upcs/cs341-project-ss2020-swift#81]

**Comment by liao21** [comment]
Both the best stat and worst stat print everything twice.

**Comment by regier21** [comment]
We are not sure if this behavior is still occurring. Will try to reproduce, but will close if this is not happening.

**Comment by regier21** [comment]
Found the issue. It is caused when a state is viewed before metadata is fetched due to a double-registration of event listeners.
