### ISSUE TITLE
State highlighting issue

### ISSUE THREAD

**Issue by regier21** [upcs/cs341-project-ss2020-swift#94]
![image](https://user-images.githubusercontent.com/42758614/79537643-34484500-8072-11ea-8a92-8cb8d0c87310.png)

When in a dark theme in edge, moving the mouse quickly over states causes multiple states to be highlighted.

**Comment by robinsph21** [comment]
Is this the new webkit based Edge or old Microsoft Edge?

**Comment by regier21** [comment]
This appears to be a browser event listener constraint without a worthwhile fix.
